version: 1
default_environment: dev
project_id: c7a2f447-8e1e-473e-a842-d06bc65e45bb
environments:
- name: dev
  config:
    plugins:
      extractors:
      - name: tap-postgres
        config:
          host: 10.20.10.0
          user: postgres
          database: pinnacledb
      loaders:
      - name: target-postgres
        config:
          host: 10.20.10.0
          database: lakedb
          user: postgres
          default_target_schema: ecart_raw
      transformers:
      - name: dbt-postgres
        config:
          host: 10.20.10.0
          user: meltano
          port: 5432
          dbname: lakedb
          schema: ecart_raw
- name: staging
- name: prod
plugins:
  extractors:
  - name: tap-postgres
    variant: meltanolabs
    pip_url: git+https://github.com/MeltanoLabs/tap-postgres.git
    select:
    - ecart-customer.*
    - ecart-fact_order.*
    - ecart-productinfo.*
    - ecart-storeinfo.*
    metadata:
      ecart-customer:
        replication-method: INCREMENTAL
        replication-key: updatedtimestamp
        #table-key-properties: [custid]
      ecart-fact_order:
        replication-method: INCREMENTAL
        replication-key: purchasetimestamp
        #table-key-properties: [orderid]
      ecart-productinfo:
        replication-method: INCREMENTAL
        replication-key: updatedtimestamp
        #table-key-properties: [productid]
      ecart-storeinfo:
        replication-method: INCREMENTAL
        replication-key: updatedtimestamp
        #table-key-properties: [storeid]
      # '*':
      #   replication-method: INCREMENTAL
  - name: tap-rest-api-msdk
    variant: widen
    pip_url: tap-rest-api-msdk
    config:
      api_url: https://earthquake.usgs.gov/fdsnws
      streams: 
      - name: us_earthquakes
        path: /event/1/query
        params:
          format: geojson
          #starttime: '2022-12-07'
          #endtime: '2022-12-08'
          starttime: '2023-09-16'
          minmagnitude: 1
        primary_keys:
        - id
        records_path: $.features[*]
        num_inference_records: 200
  - name: tap-rest-api-inc
    inherit_from: tap-rest-api-msdk
    config:
      api_url: https://earthquake.usgs.gov/fdsnws
      streams: 
      - name: us_earthquakes_inc
        path: /event/1/query
        params:
          format: geojson
          #starttime: '2022-12-07'
          #endtime: '2022-12-08'
          updatedafter: '2023-09-16'
          #orderby: time
          minmagnitude: 1
        primary_keys:
        - id
        records_path: $.features[*]
        num_inference_records: 200
        # Incremental attributes:
        #replication_key: id
        #replication_key: properties_updated
        # source_search_field: starttime
        #source_search_query:
        #start_date: '2023-09-16'
    schema:
      us_earthquakes_inc:
        properties_updated:
          type: ["integer"]
          format: date-epoch
        properties_time:
          type: ["integer"]
          format: date-time
  loaders:
  - name: target-jsonl
    variant: andyh1203
    pip_url: target-jsonl
  - name: target-postgres
    variant: meltanolabs
    pip_url: git+https://github.com/MeltanoLabs/target-postgres.git
    config:
      flattening_enabled: false
      # primary_key_required: 'true'
  transformers:
  - name: dbt-postgres
    variant: dbt-labs
    pip_url: dbt-core~=1.3.0 dbt-postgres~=1.3.0
  utilities:
  - name: airflow
    variant: apache
    pip_url: git+https://github.com/meltano/airflow-ext.git@main apache-airflow==2.3.3
      --constraint https://raw.githubusercontent.com/apache/airflow/constraints-2.3.3/constraints-no-providers-${MELTANO__PYTHON_VERSION}.txt
jobs:
#- name: tap-postgres-to-target-postgres-with-dbt
#  tasks:
#  - tap-postgres target-postgres dbt-postgres:run
- name: tap-us-earthquakes-el
  tasks:
  - tap-rest-api-msdk target-postgres 
schedules:
#- name: fivemin-postgres-load
#  interval: '*/5 * * * *'
#  job: tap-postgres-to-target-postgres-with-dbt
#- name: fivemin-earthquake-load
#  interval: '*/5 * * * *'
#  job: tap-us-earthquakes-el

